version: '3.8'

services:
  apt-price-scraper:
    build:
      context: .
    container_name: apt-scraper
    hostname: apt-scraper
    environment:
        - WEBHOOK_URL=${WEBHOOK_URL:?webhook url not set}
    deploy:
      restart_policy:
        condition: on-failure